// examples/svelte-vite/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  // import viteLogo from '/vite.svg'
  import './lib/Avatar.svelte';

  import preset from '@bbob/preset-html5'
  import html from '@bbob/html'

  const myPreset = preset.extend(defTags => {
    return ({
      ...defTags,
      avatar: (node) => {
        return ({
          ...node,
          tag: 'bb-avatar',
        })
      }
    })
  });

  let input = 'Text [b]bolded[/b] and [avatar]Some Name[/avatar]'
  $: bbcode = html(input, myPreset())
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src="/vite.svg" class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
    <div class="data">
        <div class="bbcode">
            <h2>Raw BB Code here</h2>
            <textarea name="bbcode" id="bbcode" cols="30" rows="10" bind:value={input}></textarea>
        </div>
        <div class="html">
            <h2>Generated HTML here</h2>
            <div>{@html bbcode}</div>
        </div>
    </div>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
</style>

// examples/vue3-vite/src/App.vue
<script setup lang="ts">
import preset from '@bbob/preset-vue'
import Avatar from "./components/Avatar.vue";

const myPreset = preset.extend(defTags => ({
  ...defTags,
  // bbcode tags always lowercased
  avatar: (node) => ({
    ...node,
    tag: Avatar,
  })
}))

const bbcode = 'Text [b]bolded[/b] and [avatar]Some Name[/avatar]'
const plugins = [
  myPreset()
]
</script>

<template>
  <div id="app">
    <div>
      <a href="https://vitejs.dev" target="_blank">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
    <div class="data">
      <div class="bbcode">
        <h2>Raw BB Code here</h2>
        <textarea name="bbcode" id="bbcode" cols="30" rows="10" v-model="bbcode"></textarea>
      </div>
      <div class="html">
        <h2>Generated HTML here</h2>
        <bbob-bbcode container="div" :plugins="plugins">{{ bbcode }}</bbob-bbcode>
      </div>
    </div>
    <pre class="code"></pre>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
